### PR TITLE
fix: upgrade to angular 14

### PR DESCRIPTION
**Pull request by andreivictor**
This PR contains:

- update library's `peerDependencies` in order to make it compatible with Angular13+ apps
- upgrade Angular to v14
- upgrage Jest from v27 to v28
- upgrade `typescript-eslint` to the latest version

### CODE REVIEW

**Comment by dimaslz** [comment]
hello @andreivictor, thank you for your contribution, I will take a look today.

Regards!

**Comment by dimaslz** [comment]
@andreivictor hello, thank you again for your contribution and, sorry for my delay but I was a bit busy last week.

Can you take a look and fix the tests? or maybe update to Angular 14?

**Comment by andreivictor** [comment]
Hi @dimaslz,

I fixed the issue with the Jest Tests - it seems that I forgot to update the `jest-cli` package (`jest`, `jest-cli` and `jest-environment-jsdom` must be on the same version). I was able to reproduce the error on my local machine only after removing `node_modules` and doing a clean install of the packages.

Also, I've upgraded the project to Angular v14.  When I first opened the pull request, the `@angular-eslint/...@13` packages
were not compatible with Angular v14, but in the meantime they released a new version, so the update was possible.

Thank you!

**Comment by dimaslz** [comment]
OK, is failing a test from the playground. To be pragmatic, I will merge and update after. 

Thanks, @andreivictor

**Pull request merged**
